### ISSUE TITLE
Simulation for Mid-360

### ISSUE THREAD

**Issue by fratopa** [Livox-SDK/livox_laser_simulation#10]
Good morning, 
Is there any plan to release the simulation model for the new Mid-360 sensor? If so, do you have any idea of when the simulator may be released?

**Comment by eborghi10** [comment]
Same question here :rocket:

**Comment by Awaker1** [comment]
Same question here

**Comment by engcang** [comment]
Same question here :)

**Comment by rsc9421** [comment]
Same question here

**Comment by fratopa** [comment]
Solved by the [latest commit ](https://github.com/Livox-SDK/livox_laser_simulation/commit/cf764140fe9a3bf79650c6705f1ac60a99246cf3)
