### ISSUE TITLE
Ubuntu20.04 support

### ISSUE THREAD

**Issue by Joanna-HE** [Livox-SDK/livox_laser_simulation#25]
Thanks for the great project! I want to use this project on ubuntu20.04, but have the error [World.cc:1285] Error advertising service [/House 1/shininess] after roslaunch, and the gazebo cannot present properly. Do you know how to deal with this error?

Best regards,

**Comment by georgflick** [comment]
I think the problem is the space in your service name /House 1/shininess , change it to House_1 or something like that and it should work.

**Comment by Joanna-HE** [comment]
It works for me! Thanks very much!

**Comment by QingKe-UP** [comment]
@Joanna-HE 
Hi, do you remember where you changed this service name?
Look forward to your reply.
