### ISSUE TITLE
Why is the number of points in MID-360 800,000?

### ISSUE THREAD

**Issue by liops-seungyeob** [Livox-SDK/livox_laser_simulation#29]
There are a total of 800,000 columns in the presented CSV file.

However, MID-360 is listed in the official specifications as having a resolution of 200,000 points/s.

Why do we need another pattern of 800,000 points?

**Comment by georgflick** [comment]
Because the Mid360 lidar has a non-repetitive scanning pattern. So the 800k points in the csv file represents 4 seconds of the Mid360 scanning pattern.
