### ISSUE TITLE
[catkin build error]:  "fatal error: ignition/math4/ignition/math.hh: No such file or directory"

### ISSUE THREAD

**Issue by vinsco30** [Livox-SDK/livox_laser_simulation#32]
Hi, I was trying to build your package in ROS Melodic, but every time I try to compile it I get the following error:
` fatal error: ignition/math4/ignition/math.hh: No such file or directory`
`#include <ignition/math4/ignition/math.hh>`

I tried to fix it by running: `sudo apt-get install libignition-math4-dev` but after that I got many more errors due probably to some changes in the libignition library. 
Do you know how I can fix this issue?
Thanks in advance.

**Comment by dannyXSC** [comment]
same issue, have you fixed it?

**Comment by yoursmile1999** [comment]
`sudo apt-get install ignition-citadel`
then change the include path to `#include <ignition/math6/ignition/math.hh>`
this might solve the problem

**Comment by vinsco30** [comment]
> `sudo apt-get install ignition-citadel` then change the include path to `#include <ignition/math6/ignition/math.hh>` this might solve the problem

@yoursmile1999 I've just followed your suggestion and it starts building but then tons of errors arise and it seems like there are a lot of changes between the different versions of `#include <ignition/math4/ignition/math.hh>` and `#include <ignition/math6/ignition/math.hh>`. Any suggestion about possible solution?

**Comment by vinsco30** [comment]
I found the solution: once done `sudo apt-get install ignition-citadel` and changed all the path as `#include <ignition/math6/ignition/math.hh>`, before compiling you should change the c++ version in the CMakeList.txt to 17: `add_compile_options(-std=c++17)`. Then you can run the simulation.
